<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<div>
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
펀딩 목표 금액은 500,000원 입니다. 50만원은 제작비용, 배송비용 및 기타 변동비와 수수료를 고려하여 책정되었습니다. 목표를 초과하는 금액은 초과 수량에 대한 제작비, 배송비 등으로 사용됩니다.
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
<h2>DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD</h2>
<h2>아년ㅇ안녕아년ㅇ안녕아년ㅇ안녕아년ㅇ안녕아년ㅇ안SSSSSSSSSSSSSSSSSSSSSSSSDDDDDDDDDDDDDDDD녕아년ㅇ안녕아년ㅇ안녕아년ㅇ안녕아년ㅇ안녕아년ㅇ안녕SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS</h2>
</div>
